<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // common
    'Menu' => '菜单',
    'Dashboard' => '仪表板',
    'Database' => '资料库',
    '{s1} Management' => '{s1}管理',
    'Product' => '产品',
    'User' => '用户',
    'Measure' => '单位',
    'Currency' => '货币',
    'Logistics' => '后勤资料',
    'System' => '系统',
    'Configuration' => '参数',
    'Common Resource' => '公共资源',
    'Attachement Management' => '附件管理',
    'Global Settings' => '全局配置',
    'Security' => '安全',
    'Users & Rbac' => '角色权限',
    'Sign out' => '退出帐号',
    'Config' => '配置',
    'Logs' => '日志',
    'Region' => '地区',
    'Close' => '关闭',
    'Save' => '保存',
    'Go Back' => '返回',
    'Update' => '更新',
    'Create' => '创建',
    'Cancel' => '取消',
    'Created By' => '创建者',
    'Are you sure?' => '你确定执行改动作吗',
    'Init' => '初始化',
    'Finish' => '完成',
    'View' => '查看',
    'Created At' => '创建时间',
    'Updated At' => '更新时间',
    'Assignments Role/Permissions' => '分配角色/权限',
    'Base Information' => '基本信息',
    '{s1} Album' => '{s1}相册',
    'Yes' => '是',
    'No' => '否',
    // end
    'Status' => '状态',
    'Business' => '业务',
    'Activity' => '投票活动',
    'Content' => '内容',
    'Activity Models' => '投票活动列表',
    'Activity Model' => '投票活动',
    'Type' => '类型',
    'Title' => '标题',
    'Label' => '标签',
    'Start At' => '开始时间',
    'End At' => '结束时间',
    'Vote Freq' => '投票限制',
    'Area Limit' => '地区限制',
    'Share Number' => '分享数量',
    'Income' => '收入',
    'Is Open Draw' => '是否开启抽奖',
    'Is Check' => '是否审核',
    'Start ID' => '今日之星',
    'Is Released' => '是否发布',
    'Default' => '默认',
    'Activity Player' => '活动选手',
    'Poster' => '海报',
    'Activity Player Models' => '活动选手列表',
    'Activity Player Model' => '活动选手',
    'Player Code' => '选手编号',
    'Mobile Number' => '手机号码',
    'Free Vote Number' => '免费票数',
    'Gift Vote Number' => '礼物票数',
    'View Number' => '浏览次数',
    'Total Vote Number' => '总投票数',
    'Checked' => '已审核',
    'Not Check' => '为审核',
    'User Name' => '用户名称',
    'Sys Entry' => '系统报名',
    'User Entry' => '用户报名',
    'Entry Type' => '报名类型',
    'Fe User' => '用户',
    'Fe User Models' => '用户列表',
    'Fe User Model' => '用户',
    'User Registration' => '用户注册',
    'Sys Registration' => '系统注册',
    'Username' => '用户名字',
    'Registration Ip' => '注册IP',
    'Registration Src Type' => '注册类型',
    'Last Login Ip' => '上次登录IP',
    'Active' => '活动',
    'Inactive' => '停用',
    'User Avatar Add' => '用户添加头像',
    'Search {s1}' => '搜索{s1}',
    'QR Code' => '二维码',
    'Browser' => '访问',
    'Players' => '选手',
    '' => '',
];

