<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Your verify code is:{s1}' => '【可比科技】您的验证码是：{s1}',
    'Have new distributors:{s1}, cell phone number:{s2} apply to join, please login background review' => '有新的代理商{s1}、手机号{s2}申请加入，请登入后台审核。【北欧私享馆】',
    'Have new franchisee:{s1}, cell phone number:{s2} apply to join, please login background review' => '有新的加盟商{s1}、手机号{s2}申请加入，请登入后台审核。【北欧私享馆】',
    'Have new shop:{s1}, cell phone number:{s2} apply to join, please login background review' => '有新的专卖店{s1}、手机号{s2}申请加入，请登入后台审核。【北欧私享馆】',

    'Apply to join the result notification:respect of distributors:{s1}'=>'申请结果通知:尊敬的代理商{s1}，您的申请已经审核通过，欢迎您的加入。【北欧私享馆】',
    'Apply to join the result notification:respect of franchisee:{s1}'=>'申请结果通知:尊敬的加盟商{s1}，您的申请已经审核通过，欢迎您的加入。【北欧私享馆】',
    'Apply to join the result notification:respect of shop:{s1}'=>'申请结果通知:尊敬的店长{s1}，您的申请已经审核通过，欢迎您的加入。【北欧私享馆】',
    'Apply to join the result notification:respect of bizmanager:{s1}'=>'申请结果通知:尊敬的业务经理{s1}，您的申请已经审核通过，欢迎您的加入。【北欧私享馆】',

    'Dear applicant{s1}, your application is not approved'=>'申请结果通知:尊敬的申请者{s1}，您的申请未获得通过，请联系客户经理了解详细情况【北欧私享馆】',
    'Distributors:{s1} delete franchisees:{s2}application'=>'代理商{s1}申请删除加盟商{s2}，请登入后台审核【北欧私享馆】',

    'Your draining member is in {s1} in {s2} happening consumption, you can get {s3} yuan Commission, please go to store to receive in time'=>'您引流的会员于{s1}在{s2}发生消费，您可以获得{s3}元佣金，请及时到店领取。【北欧私享馆】',
    'The mobile phone number is {s1}, and the Commissioner receives {s3} yuan Commission at {s2}'=>'手机号为{s1}的专员于{s2}领取{s3}元佣金',
    'Default'=>'未知类型',
    ''=>'',
];