<?php
//
// $wjs = Yii::$app->wechat->app->js;
// $js = "";
// $js .= "wx.config(" . $wjs->config([
//             'scanQRCode',
//             'checkJsApi',
//             'onMenuShareTimeline',
//             'onMenuShareAppMessage',
//             'onMenuShareQQ',
//             'onMenuShareWeibo',
//             'onMenuShareQZone',
//             'hideMenuItems',
//             'showMenuItems',
//             'hideAllNonBaseMenuItem',
//             'showAllNonBaseMenuItem',
//             'translateVoice',
//             'startRecord',
//             'stopRecord',
//             'onVoiceRecordEnd',
//             'playVoice',
//             'onVoicePlayEnd',
//             'pauseVoice',
//             'stopVoice',
//             'uploadVoice',
//             'downloadVoice',
//             'chooseImage',
//             'previewImage',
//             'uploadImage',
//             'downloadImage',
//             'getNetworkType',
//             'openLocation',
//             'getLocation',
//             'hideOptionMenu',
//             'showOptionMenu',
//             'closeWindow',
//             'scanQRCode',
//             'chooseWXPay',
//             'openProductSpecificView',
//             'addCard',
//             'chooseCard',
//             'openCard',], false) . ")";
// $this->registerJs($js);
