<?php

namespace frontend\components\actions;

use common\models\c2\entity\ActivityPlayerModel;
use common\models\c2\statics\ActivityPlayerState;
use cza\base\models\statics\ResponseDatum;
use Yii;
use yii\web\Response;

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/10 0010
 * Time: 下午 15:34
 */
class VoteAction extends \yii\base\Action
{
    public $playerId;

    public function run()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $params = Yii::$app->request->post();
        $playerModel = ActivityPlayerModel::findOne($params['id']);
        if ($playerModel->state == ActivityPlayerState::STATE_NOT_CHECK) {
            return ResponseDatum::getErrorDatum(['message' => Yii::t('app.c2', 'Player disable.')], $playerModel);
        }
        $activityModel = $playerModel->activity;
        // $user = \Yii::$app->user->identity;
        $key = 'user:' . 1 . '/' . 'player:' . $playerModel->id . '/' . date('Y-m-d', time());
        $redis = \Yii::$app->redis;
        $votedNum = $redis->get($key);
        if ($votedNum < $activityModel->vote_number_limit) {
            $redis->incr($key);
            $redis->expire($key, 60 * 60 * 24);
            $playerModel->updateCounters(['free_vote_number' => 1]);
            $playerModel->updateCounters(['total_vote_number' => 1]);
            $activityModel->updateCounters(['vote_number' => 1]);
            // $user->updateCounters(['score' => 1]);
            $responseData = ResponseDatum::getSuccessDatum([
                'message' => Yii::t('app.c2', 'Vote Success')
            ], $playerModel);
        } else {
            $responseData = ResponseDatum::getErrorDatum([
                'message' => Yii::t('app.c2', 'You can vote {s1} once day.', [
                    's1' => $activityModel->vote_number_limit
                ])
            ], $playerModel);
        }
        return $responseData;
    }

    protected function beforeRun()
    {
        // if (Yii::$app->user->isGuest) {
        //     Yii::info('before vote');
        //     if(!Yii::$app->wechat->isAuthorized()) {
        //         Yii::info('在微信客户端');
        //         return Yii::$app->wechat->authorizeRequired()->send();
        //     }
        // }
        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }
}