<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Base Info' => '基本信息',
    'Multiple Language' => '多语言录入',
    'Search' => '查找',
    'Settings' => '设置',
    'Account Settings' => '资料',
    'UI Language' => '界面语言',
    'System' => '系统',
    'Guest' => '客人',
    'Username' => '用户',
    'Password' => '密码',
    'Remember Me' => '下回自动登录',
    'Verification Code Input' => '请输入右边验证码',
    'Refresh Verification Code' => '点击刷新验证码',
    'Incorrect username or password.' => '用户名或密码不正确',
    'Menu' => '菜单',
    'User Login' => '用户登录',
    'Not Registred?' => '还没帐号？',
    'Register here' => '请点这里注册',
    'Navigation Bar' => '导航条',
    'All franchisee' => '所有加盟商',
    'Distributor Stat Growths' => '代理商日报表',
    'Franchisee Stat Growths' => '加盟商日报表',
    'Shop Stat Growths' => '店铺日报表',
    'Info' => '编辑',
    'View' => '查看',
];
