<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // common
    'Menu' => '菜单',
    'Dashboard' => '仪表板',
    'Database' => '资料库',
    '{s1} Management' => '{s1}管理',
    'Product' => '产品',
    'User' => '用户',
    'Measure' => '单位',
    'Currency' => '货币',
    'Logistics' => '后勤资料',
    'System' => '系统',
    'Configuration' => '参数',
    'Common Resource' => '公共资源',
    'Attachement Management' => '附件管理',
    'Global Settings' => '全局配置',
    'Security' => '安全',
    'Users & Rbac' => '角色权限',
    'Sign out' => '退出帐号',
    'Config' => '配置',
    'Logs' => '日志',
    'Region' => '地区',
    'Close' => '关闭',
    'Save' => '保存',
    'Go Back' => '返回',
    'Update' => '更新',
    'Create' => '创建',
    'Cancel' => '取消',
    'Created By' => '创建者',
    'Are you sure?' => '你确定执行改动作吗',
    'Init' => '初始化',
    'Finish' => '完成',
    'View' => '查看',
    'Created At' => '创建时间',
    'Updated At' => '更新时间',
    'Assignments Role/Permissions' => '分配角色/权限',
    'Base Information' => '基本信息',
    '{s1} Album' => '{s1}相册',
    'Yes' => '是',
    'No' => '否',
    // end
    'Activity disable.' => '活动不存在或已结束。',
    'th {s1}' => '第{s1}名',
    'Search' => '搜索',
    'Input player code or name to search...' => '输入选手编号或名字搜索...',
    '{s1} Votes' => '{s1}票',
    'Vote It' => '给TA投票',
    '' => '',
];

