<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // common
    'Menu' => '菜单',
    'Dashboard' => '仪表板',
    'Database' => '资料库',
    '{s1} Management' => '{s1}管理',
    'Product' => '产品',
    'User' => '用户',
    'Measure' => '单位',
    'Currency' => '货币',
    'Logistics' => '后勤资料',
    'System' => '系统',
    'Configuration' => '参数',
    'Common Resource' => '公共资源',
    'Attachement Management' => '附件管理',
    'Global Settings' => '全局配置',
    'Security' => '安全',
    'Users & Rbac' => '角色权限',
    'Sign out' => '退出帐号',
    'Config' => '配置',
    'Logs' => '日志',
    'Region' => '地区',
    'Close' => '关闭',
    'Save' => '保存',
    'Go Back' => '返回',
    'Update' => '更新',
    'Create' => '创建',
    'Cancel' => '取消',
    'Created By' => '创建者',
    'Are you sure?' => '你确定执行改动作吗',
    'Init' => '初始化',
    'Finish' => '完成',
    'View' => '查看',
    'Created At' => '创建时间',
    'Updated At' => '更新时间',
    'Assignments Role/Permissions' => '分配角色/权限',
    'Base Information' => '基本信息',
    '{s1} Album' => '{s1}相册',
    'Yes' => '是',
    'No' => '否',
    // end
    'Activity disable.' => '活动不存在或已结束。',
    'th {s1}' => '第{s1}名',
    'Search' => '搜索',
    'Input player code or name to search...' => '输入选手编号或名字搜索...',
    '{s1} Votes' => '{s1}票',
    'Vote It' => '投票',
    'Total View' => '总浏览量',
    'Total Vote' => '总投票量',
    'Total Share' => '总分享量',
    'You can vote {s1} once day.' => '一天只能投{s1}票奥。',
    'Vote Success' => '投票成功',
    'Rank' => '排行榜',
    'Lottery' => '抽奖',
    'Apply' => '报名',
    'Mine' => '我的',
    'Activity Introduce' => '-- 活动说明 --',
    'Free Vote' => '投Ta一票',
    'Gift Vote' => '礼物投票',
    'Player disable.' => '选手审核中或不存在。',
    'Vote Number' => '票数',
    'Current Rank' => '当前排名',
    'Diff Before Player Vote' => '与前一名相差',
    'Diff After Player Vote' => '与后一名相差',
    'Tips' => '提示',
    'Vote' => '票',
    'Require Redis Component Support!' => '投票服务开启失败',
    'Title' => '标题',
    'Content' => '内容',
    'Photo Add' => '图片添加',
    'Photo must upload.' => '请先添加图片。',
    'Title like that.' => '填写标题，如：我是xx，请投我一票谢谢！',
    'Content like that.' => '填写内容',
    'Apply successful.' => '报名成功！',
    'Submit Application' => '提交申请',
    'Vote Fail' => '投票失败',
    'Pay Body' => '虹之玉-摇摇乐-礼物赠送',
    'Gift to {s1} pay for {s2}' => '正在参与{s1}活动，为选手赠送【{s2}】礼物。',
    'th' => '名',
    'Username Label' => '姓名',
    '{s1} inc{s2}' => '{s1} +{s2}票',
    'inc{s1}' => '+{s1}票',
    'Newest voted.' => '他们刚刚给ta投票!',
    'Generate Poster' => '生成海报',
    'Poster tips.' => '提示：长按图片保存到手机。',
    'My Poster' => '二维码海报',
    'Lottery disable.' => '该活动尚未开通抽奖，请敬请期待~',
    'Current Point:' => '当前积分：',
    'Rules' => '规则',
    'Go Drawing' => '开始抽奖',
    'More Players' => '查看更多',
    'Drawn' => '中奖',
    'Last Page' => '上一页',
    'Next Page' => '下一页',
    'My Prizes' => '中奖记录',
    'Checked' => '已审核',
    'Not Check' => '待审核',
    '' => '',
];

