<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/11
 * Time: 22:06
 */

namespace frontend\widgets;


use common\models\c2\entity\ActivityModel;
use yii\base\Widget;

class GiftsGridView extends Widget
{
    /**
     * @var ActivityModel
     */
    public $activityModel;
    public $playerId;

    public $template = '<div class="col-xs-4" style="padding: 0">
                            <div class="gift-item">
                                <div class="gift-photo">
                                    <span class="label label-success">{score}</span>
                                    <img style="width: 60px" align="center" src="{photo}">
                                </div>
                                <p>{title}</p>
                                <button data-value="{gift_id}" class="btn btn-sm btn-success gift" style="width: 80%;line-height: 1;">赠送</button>
                            </div>
                        </div>';

    public function run()
    {
        $models = $this->activityModel->getActivityGifts();
        $rows = count($models) / 3;
        // $remain = count($models) % 3;
        $result = "";
        for ($i = 0; $i < $rows; $i++) {
            $result .= '<div class="row" style="margin: 0">';
            for ($j = $i * 3; $j < ($i + 1) * 3; $j++) {
                if (!is_null($models[$j])) {
                    $result .= strtr($this->template, [
                        '{score}' => '+' . ($models[$j]->obtain_score + 0) . '积分',
                        '{photo}' => $models[$j]->getThumbnailUrl(),
                        '{title}' => $models[$j]->name . ' +' . $models[$j]->obtain_vote_number . '票',
                        '{gift_id}' => $models[$j]->id,
                    ]);
                }

            }
            $result .= '</div>';
        }
        echo $result;

        // return $this->render('GiftsGridView', [
        // ]);
    }

    public function afterRun($result)
    {
        $view = $this->getView();
        $js = "";
        $js .= "
                $('.gift').on('click', function (e) {
                    console.log();
                        $.ajax({
                        type: 'post',
                        url: '/wechat/default/payment',
                        dataType: 'json',
                        data: {player_id:'{$this->playerId}', gift_id: jQuery(e.currentTarget).attr('data-value')},
                        beforeSend: function() {
                            console.log('before')
                        },
                        success: function(res) {
                            console.log(res);
                        },
                        error: function(res) {
                            if (res.status === 500) {
                                $('#content-modal').find('.modal-title').html('提示');
                                // $('#content-modal').modal('show').find('.modal-body').html(res.responseText);
                                $('#content-modal').modal('show').find('.modal-body').html('服务器开小差');
                            }
                        },
                        complete: function() {
                            console.log('done')
                        }
                    });
                })
                ";
        $view->registerJs($js);
        return parent::afterRun($result); // TODO: Change the autogenerated stub
    }

}