<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/11 0011
 * Time: 上午 9:30
 */
namespace frontend\widgets;

class PlayerSearch extends \yii\base\Widget
{

    public function run()
    {
        // parent::run(); // TODO: Change the autogenerated stub
        return $this->render('PlayerSearch');
    }

}